Add test to show issue with BPMN Transactions:
[main] [ERROR] context - ENGINE-16006 BPMN Stack Trace:
	Transaction_02x25sb (transition-notifiy-listener-start,
ScopeExecution[7])
	Transaction_02x25sb
	  ^
	  |
	StartEvent_0hjbp2y

[main] [ERROR] context - ENGINE-16004 Exception while closing command
context: ENGINE-03036 Cannot cast
'org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl@349df0df'
to 'FlowElement'. Element is of type 'transaction' with namespace
'http://www.omg.org/spec/BPMN/20100524/MODEL'.
org.camunda.bpm.engine.ProcessEngineException: ENGINE-03036 Cannot cast
'org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl@349df0df'
to 'FlowElement'. Element is of type 'transaction' with namespace
'http://www.omg.org/spec/BPMN/20100524/MODEL'.
	at
org.camunda.bpm.engine.impl.db.EnginePersistenceLogger.castModelInstanceException(EnginePersistenceLogger.java:346)
	at
org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.getBpmnModelElementInstance(ExecutionEntity.java:1552)
	at
org.camunda.bpm.extension.reactor.bus.SelectorBuilder.extractTypeName(SelectorBuilder.java:222)
	at
org.camunda.bpm.extension.reactor.bus.SelectorBuilder.selector(SelectorBuilder.java:52)
	at
org.camunda.bpm.extension.reactor.bus.CamundaEventBus.notify(CamundaEventBus.java:61)
	at
org.camunda.bpm.extension.reactor.bus.CamundaEventBus$2.notify(CamundaEventBus.java:94)
	at
org.camunda.bpm.extension.reactor.bus.CamundaEventBus$2.notify(CamundaEventBus.java:1)
	at
org.camunda.bpm.engine.impl.core.instance.CoreExecution.invokeListener(CoreExecution.java:93)
	at
org.camunda.bpm.engine.impl.core.operation.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:51)
	at
org.camunda.bpm.engine.impl.interceptor.AtomicOperationInvocation.execute(AtomicOperationInvocation.java:81)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.invokeNext(CommandContext.java:180)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.performNext(CommandContext.java:159)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:134)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:124)
	at
org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:505)
	at
org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:480)
	at
org.camunda.bpm.engine.impl.core.operation.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:58)
	at
org.camunda.bpm.engine.impl.interceptor.AtomicOperationInvocation.execute(AtomicOperationInvocation.java:81)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.invokeNext(CommandContext.java:180)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.performNext(CommandContext.java:159)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:134)
	at
org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:494)
	at
org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:471)
	at
org.camunda.bpm.engine.impl.pvm.runtime.operation.PvmAtomicOperationTransitionCreateScope.scopeCreated(PvmAtomicOperationTransitionCreateScope.java:34)
	at
org.camunda.bpm.engine.impl.pvm.runtime.operation.PvmAtomicOperationCreateScope.execute(PvmAtomicOperationCreateScope.java:49)
	at
org.camunda.bpm.engine.impl.pvm.runtime.operation.PvmAtomicOperationCreateScope.execute(PvmAtomicOperationCreateScope.java:23)
	at
org.camunda.bpm.engine.impl.interceptor.AtomicOperationInvocation.execute(AtomicOperationInvocation.java:81)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.invokeNext(CommandContext.java:180)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.performNext(CommandContext.java:167)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:134)
	at
org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:494)
	at
org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:471)
	at
org.camunda.bpm.engine.impl.pvm.runtime.PvmExecutionImpl.start(PvmExecutionImpl.java:229)
	at
org.camunda.bpm.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:75)
	at
org.camunda.bpm.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:35)
	at
org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:24)
	at
org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:95)
	at
org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at
org.camunda.bpm.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:66)
	at
org.camunda.bpm.extension.reactor.process.BPMNTransactionProcessTest.start_bpmn_transaction_process(BPMNTransactionProcessTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassCastException:
org.camunda.bpm.model.xml.impl.instance.ModelElementInstanceImpl cannot
be cast to org.camunda.bpm.model.bpmn.instance.FlowElement
	at
org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity.getBpmnModelElementInstance(ExecutionEntity.java:1548)
	... 64 more